name: Weekly IP Filtering and Testing

on:
  schedule:
    # 每周一凌晨 00:00 UTC 运行
    - cron: '0 0 * * 1'
  workflow_dispatch:
    # 支持手动触发
  push:
    branches:
      - main
    paths-ignore:
      # 忽略脚本更新，避免触发自动运行
      - 'ip-filter-speedtest-api.py'

jobs:
  ip-filtering:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 安装依赖
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests charset-normalizer geoip2==4.8.0 maxminddb>=2.0.0 packaging>=21.3

      # 调试环境
      - name: Debug Environment
        run: |
          echo "SHLVL=$SHLVL"
          pwd
          ls -l
          command -v stdbuf || echo "stdbuf not found"

      # 准备测速脚本并设置执行权限
      - name: Prepare Speedtest Scripts
        run: |
          # 如果 iptest.sh 不存在，创建模拟脚本
          if [ ! -f iptest.sh ]; then
            echo '#!/bin/sh' > iptest.sh
            echo 'echo "ip,port,latency,speed" > ip.csv' >> iptest.sh
            echo 'while IFS=" " read -r ip port; do' >> iptest.sh
            echo '  echo "$ip,$port,10ms,100Mbps" >> ip.csv' >> iptest.sh
            echo 'done < ip.txt' >> iptest.sh
          fi
          # 如果 iptest 不存在，创建符号链接
          if [ ! -f iptest ]; then
            ln -sf iptest.sh iptest
          fi
          # 确保脚本具有执行权限
          chmod +x iptest.sh
          chmod +x iptest
          ls -l iptest.sh iptest
          echo "SHLVL after preparing scripts: $SHLVL"

      # 测试测速脚本
      - name: Test Speedtest Script
        run: |
          ./iptest.sh
          cat ip.csv || echo "ip.csv not generated"

      # 运行 IP 筛选和测速脚本
      - name: Run IP Filtering Script
        env:
          MAXMIND_LICENSE_KEY: ${{ secrets.MAXMIND_LICENSE_KEY }}
        run: |
          export SHLVL=1  # 重置 SHLVL
          python ip-filter-speedtest-api.py --update-geoip

      # 检查生成的文件
      - name: Verify Output Files
        run: |
          ls -l ip.txt ip.csv ips.txt || echo "Some output files are missing"

      # 配置 Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 提交和推送更改
      - name: Commit and Push Changes
        run: |
          git add ip.txt ip.csv ips.txt
          git commit -m "Update IP data - $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
