name: Proxy IP Check

permissions:
  contents: write  # 授予仓库内容的写权限，允许 git push

on:
  push:
    branches:
      - main
    paths:
      - 'input.csv'
      - 'ip-filter-speedtest-api.py'
      - 'iptest.sh'
  pull_request:
    branches:
      - main
    paths:
      - 'input.csv'
      - 'ip-filter-speedtest-api.py'
      - 'iptest.sh'
  schedule:
    - cron: '0 0 * * 1'  # 每周一 UTC 时间 00:00 运行
  workflow_dispatch:

jobs:
  proxy-ip-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests charset-normalizer

      - name: Make iptest.sh executable
        run: |
          chmod +x iptest.sh
          chmod +x iptest || echo "iptest binary not found"

      - name: Run proxy IP check
        timeout-minutes: 10
        run: |
          echo "Start time: $(date)"
          echo "开始时间: $(date)"
          python3 ip-filter-speedtest-api.py
          echo "结束时间: $(date)"

      - name: Commit and push generated files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ip.txt ip.csv ips.txt speedtest.log country_cache.json
          git commit -m "Update generated files from proxy IP check" || echo "No changes to commit"
          git push || echo "No changes to push"

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: proxy-ip-results
          path: |
            ip.txt
            ip.csv
            ips.txt
            speedtest.log
            country_cache.json
